name: distributed
author: ""
clients:
  node:
    runtime: node
  local:
    runtime: browser
  web:
    runtime: browser
  noclient:
    runtime: browser
    default: true
  update-config:
    runtime: node
